plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.compose")
}

android {
    namespace = "com.shunkan.sync"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.shunkan.sync"
        // Android 10 (API 29) is where background clipboard reads were REMOVED:
        // only the default IME or the focused app may read the clipboard. The
        // old comment had this backwards. See CAPTURE-DESIGN.md — the IME,
        // share target and tile in the manifest exist because of this, not in
        // spite of it.
        minSdk = 29
        targetSdk = 35
        versionCode = 1
        versionName = "0.1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        // NDK ABI filters for shunkan-core native library
        ndk {
            abiFilters += listOf("arm64-v8a", "x86_64")
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
    }

    // cargo-ndk writes libshunkan_core.so here; see scripts/build-android.sh.
    sourceSets["main"].jniLibs.srcDirs("src/main/jniLibs")

    packaging {
        // JNA ships per-ABI natives; keep only the ABIs we build for.
        jniLibs {
            useLegacyPackaging = false
        }
    }

    lint {
        // The generated UniFFI bindings are not ours to lint.
        disable += "TypographyEllipsis"
    }
}

dependencies {
    // Jetpack Compose BOM
    val composeBom = platform("androidx.compose:compose-bom:2024.06.00")
    implementation(composeBom)

    // Compose UI
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.activity:activity-compose:1.9.0")
    implementation("androidx.lifecycle:lifecycle-runtime-compose:2.8.3")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.3")

    // Core AndroidX
    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.appcompat:appcompat:1.7.0")

    // Navigation
    implementation("androidx.navigation:navigation-compose:2.7.7")

    // Coroutines
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1")

    // UniFFI's Kotlin bindings talk to libshunkan_core.so over JNA, so JNA
    // must be present at runtime — the @aar variant carries the native parts
    // for each ABI. Without it the bindings compile and then fail on first call.
    implementation("net.java.dev.jna:jna:5.14.0@aar")

    // Generated by scripts/build-android.sh into:
    //   app/src/main/java/uniffi/shunkan_core/shunkan_core.kt
    //   app/src/main/jniLibs/<abi>/libshunkan_core.so

    // Testing
    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test.ext:junit:1.2.1")
    androidTestImplementation("androidx.compose.ui:ui-test-junit4")
    debugImplementation("androidx.compose.ui:ui-tooling")
}
